on: ["push"]
name: "CI"

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v1"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"

      - name: "Install dependencies"
        run: "composer update --no-ansi --no-interaction --no-progress"

      - name: "Run tests"
        run: "composer tests"

      - name: "Upload code coverage"
        if: "matrix.php-version == '7.4'"
        uses: codecov/codecov-action@v1
        with:
          file: "coverage.xml"
          fail_ci_if_error: true

  phpstan:
    name: "PHPStan"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v1"
        with:
          php-version: "7.4"

      - name: "Install dependencies"
        run: "composer update --no-ansi --no-interaction --no-progress"

      - name: "Run PHPStan"
        run: "composer phpstan"

  codesniffer:
    name: "Coding standard"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v1"
        with:
          php-version: "7.4"

      - name: "Install dependencies"
        run: "composer update --no-ansi --no-interaction --no-progress"

      - name: "Run CodeSniffer"
        run: "composer check"
