on:
  - "push"
  - "pull_request"

name: "CI"

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v1"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"

      - name: "Install dependencies"
        run: "composer install"
